import {
  MusicModelDefinition,
  MusicProviderDefinition,
} from './music-runtime.types';

export const MUSIC_PROVIDERS: MusicProviderDefinition[] = [
  {
    id: 'diffsinger',
    name: 'DiffSinger',
    description: 'Singing voice synthesis with isolated HiFi-GAN runtime.',
    runtimeInstalled: true,
    dockerService: 'diffsinger',
    containerName: 'harmonia-diffsinger',
    composeProfile: 'model-diffsinger',
  },
  {
    id: 'musicgen',
    name: 'MusicGen',
    description: 'Meta AudioCraft music generation baseline.',
    runtimeInstalled: false,
  },
  {
    id: 'stable-audio-3',
    name: 'Stable Audio 3',
    description: 'Fast local music and audio generation.',
    runtimeInstalled: false,
  },
  {
    id: 'ace-step-1.5',
    name: 'ACE-Step 1.5',
    description: 'Full-song generation with lyrics, vocals and editing.',
    runtimeInstalled: false,
  },
  {
    id: 'diffrhythm',
    name: 'DiffRhythm',
    description: 'Full-length lyric-conditioned song generation.',
    runtimeInstalled: false,
  },
  {
    id: 'heartmula',
    name: 'HeartMuLa',
    description: 'Multilingual lyric-conditioned music foundation model.',
    runtimeInstalled: false,
  },
  {
    id: 'songgeneration',
    name: 'SongGeneration',
    description: 'Tencent full-song vocal and accompaniment generation.',
    runtimeInstalled: false,
  },
  {
    id: 'yue2',
    name: 'YuE2',
    description: 'High-capacity full-song generation with symbolic planning.',
    runtimeInstalled: false,
  },
];

export const MUSIC_MODELS: MusicModelDefinition[] = [
  {
    id: 'diffsinger-acoustic-hifigan',
    providerId: 'diffsinger',
    name: 'Acoustic + HiFi-GAN',
    availability: 'installed',
    minVramGb: 6,
    recommendedVramGb: 8,
    capabilities: ['vocals', 'lyrics', 'singing-synthesis'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
    notes: 'Requires compatible local DiffSinger acoustic checkpoints.',
  },

  {
    id: 'musicgen-small',
    providerId: 'musicgen',
    name: 'MusicGen Small',
    modelSize: '300M',
    availability: 'planned',
    minVramGb: 4,
    recommendedVramGb: 6,
    maxDurationSeconds: 120,
    capabilities: ['instrumental', 'text-to-music'],
    runtimeCost: 'local-free',
    commercialUse: 'restricted',
  },
  {
    id: 'musicgen-stereo-medium',
    providerId: 'musicgen',
    name: 'MusicGen Stereo Medium',
    modelSize: '1.5B',
    availability: 'planned',
    minVramGb: 8,
    recommendedVramGb: 10,
    maxDurationSeconds: 120,
    capabilities: ['instrumental', 'stereo', 'text-to-music'],
    runtimeCost: 'local-free',
    commercialUse: 'restricted',
  },

  {
    id: 'stable-audio-3-small-music',
    providerId: 'stable-audio-3',
    name: 'Small Music',
    modelSize: '433M',
    availability: 'planned',
    minVramGb: 0,
    recommendedVramGb: 0,
    maxDurationSeconds: 120,
    capabilities: ['instrumental', 'text-to-music', 'cpu-capable'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
  },
  {
    id: 'stable-audio-3-medium',
    providerId: 'stable-audio-3',
    name: 'Medium',
    modelSize: '1.4B',
    availability: 'planned',
    minVramGb: 7,
    recommendedVramGb: 8,
    maxDurationSeconds: 380,
    capabilities: ['instrumental', 'text-to-music', 'long-form'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
  },
  {
    id: 'stable-audio-3-large-api',
    providerId: 'stable-audio-3',
    name: 'Large',
    modelSize: '2.7B',
    availability: 'api-only',
    maxDurationSeconds: 380,
    capabilities: ['instrumental', 'text-to-music', 'long-form'],
    runtimeCost: 'hosted-paid',
    commercialUse: 'review-required',
    notes: 'Visible for comparison; current open repository does not provide local Large inference.',
  },

  {
    id: 'acestep-v15-turbo-06b',
    providerId: 'ace-step-1.5',
    name: 'Turbo + 0.6B LM',
    modelSize: '2B + 0.6B',
    availability: 'planned',
    minVramGb: 8,
    recommendedVramGb: 10,
    maxDurationSeconds: 480,
    capabilities: ['vocals', 'lyrics', 'instrumental', 'editing', 'reference-audio'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
  },
  {
    id: 'acestep-v15-sft-06b',
    providerId: 'ace-step-1.5',
    name: 'SFT + 0.6B LM',
    modelSize: '2B + 0.6B',
    availability: 'planned',
    minVramGb: 8,
    recommendedVramGb: 10,
    maxDurationSeconds: 480,
    capabilities: ['vocals', 'lyrics', 'instrumental', 'editing', 'reference-audio'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
  },
  {
    id: 'acestep-v15-sft-17b',
    providerId: 'ace-step-1.5',
    name: 'SFT + 1.7B LM',
    modelSize: '2B + 1.7B',
    availability: 'planned',
    minVramGb: 12,
    recommendedVramGb: 12,
    maxDurationSeconds: 480,
    capabilities: ['vocals', 'lyrics', 'instrumental', 'editing', 'reference-audio'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
  },
  {
    id: 'acestep-v15-xl-17b',
    providerId: 'ace-step-1.5',
    name: 'XL + 1.7B LM',
    modelSize: '4B + 1.7B',
    availability: 'planned',
    minVramGb: 16,
    recommendedVramGb: 20,
    maxDurationSeconds: 480,
    capabilities: ['vocals', 'lyrics', 'instrumental', 'editing', 'reference-audio'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
  },
  {
    id: 'acestep-v15-xl-4b',
    providerId: 'ace-step-1.5',
    name: 'XL + 4B LM',
    modelSize: '4B + 4B',
    availability: 'planned',
    minVramGb: 24,
    recommendedVramGb: 24,
    maxDurationSeconds: 600,
    capabilities: ['vocals', 'lyrics', 'instrumental', 'editing', 'reference-audio'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
  },

  {
    id: 'diffrhythm-v12-base',
    providerId: 'diffrhythm',
    name: 'v1.2 Base',
    availability: 'planned',
    minVramGb: 8,
    recommendedVramGb: 10,
    maxDurationSeconds: 95,
    capabilities: ['vocals', 'lyrics', 'instrumental', 'continuation', 'editing'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
  },
  {
    id: 'diffrhythm-v12-full',
    providerId: 'diffrhythm',
    name: 'v1.2 Full',
    availability: 'planned',
    minVramGb: 10,
    recommendedVramGb: 12,
    maxDurationSeconds: 285,
    capabilities: ['vocals', 'lyrics', 'instrumental', 'continuation', 'editing', 'long-form'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
  },

  {
    id: 'heartmula-3b-lazy',
    providerId: 'heartmula',
    name: '3B + HeartCodec (Lazy Load)',
    modelSize: '3B',
    availability: 'planned',
    minVramGb: 8,
    recommendedVramGb: 10,
    maxDurationSeconds: 240,
    capabilities: ['vocals', 'lyrics', 'multilingual', 'full-song'],
    runtimeCost: 'local-free',
    commercialUse: 'allowed',
  },
  {
    id: 'heartmula-3b-resident',
    providerId: 'heartmula',
    name: '3B + HeartCodec (Resident)',
    modelSize: '3B',
    availability: 'planned',
    minVramGb: 12,
    recommendedVramGb: 12,
    maxDurationSeconds: 240,
    capabilities: ['vocals', 'lyrics', 'multilingual', 'full-song'],
    runtimeCost: 'local-free',
    commercialUse: 'allowed',
  },
  {
    id: 'heartmula-7b',
    providerId: 'heartmula',
    name: '7B',
    modelSize: '7B',
    availability: 'unreleased',
    minVramGb: 24,
    recommendedVramGb: 24,
    maxDurationSeconds: 240,
    capabilities: ['vocals', 'lyrics', 'multilingual', 'full-song'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
    notes: 'Listed for future compatibility; public 7B weights are not currently released.',
  },

  {
    id: 'songgeneration-base-new',
    providerId: 'songgeneration',
    name: 'Base New (EN/ZH)',
    availability: 'planned',
    minVramGb: 10,
    recommendedVramGb: 10,
    maxDurationSeconds: 150,
    capabilities: ['vocals', 'lyrics', 'instrumental', 'separate-stems'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
  },
  {
    id: 'songgeneration-base-full',
    providerId: 'songgeneration',
    name: 'Base Full',
    availability: 'planned',
    minVramGb: 12,
    recommendedVramGb: 18,
    maxDurationSeconds: 270,
    capabilities: ['vocals', 'lyrics', 'instrumental', 'separate-stems', 'long-form'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
  },
  {
    id: 'songgeneration-large',
    providerId: 'songgeneration',
    name: 'Large',
    availability: 'planned',
    minVramGb: 22,
    recommendedVramGb: 28,
    maxDurationSeconds: 270,
    capabilities: ['vocals', 'lyrics', 'instrumental', 'separate-stems', 'long-form'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
  },
  {
    id: 'songgeneration-v2-large',
    providerId: 'songgeneration',
    name: 'v2 Large',
    availability: 'planned',
    minVramGb: 22,
    recommendedVramGb: 28,
    maxDurationSeconds: 270,
    capabilities: ['vocals', 'lyrics', 'instrumental', 'multilingual', 'long-form'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
  },

  {
    id: 'yue2-3b',
    providerId: 'yue2',
    name: 'YuE2 3B',
    modelSize: '3B',
    availability: 'planned',
    minVramGb: 24,
    recommendedVramGb: 24,
    capabilities: ['vocals', 'lyrics', 'symbolic-planning', 'full-song', 'stereo'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
  },
  {
    id: 'yue-legacy-full-multisession',
    providerId: 'yue2',
    name: 'YuE Legacy Full Multi-session',
    availability: 'planned',
    minVramGb: 80,
    recommendedVramGb: 80,
    capabilities: ['vocals', 'lyrics', 'full-song', 'research'],
    runtimeCost: 'local-free',
    commercialUse: 'review-required',
    notes: 'High-capacity research option for long multi-session generation.',
  },
];
