packages:
  - .
  - packages/*

allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  bcrypt: true
  mongodb-memory-server: true
  '@parcel/watcher@2.5.1 || 2.6.0': true
  'unrs-resolver@1.11.1 || 1.12.2': true

strictDepBuilds: true
