name: Test Mongoose Models

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-mongoose:
    name: Run memory-server test
    runs-on: ubuntu-latest
    env:
      MONGOMS_VERSION: "7.0.14"
      MONGOMS_DISTRO: "ubuntu-22.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
      
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.23.0
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run memory-server test
        run: pnpm test:mongo
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mongoose-test-results
          path: scripts/test_mongoose_memory.js
